# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\all_desing\ui\desing.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from typing import NoReturn

class Ui_MainMenu(object):
    def setupUi(self, MainMenu) -> NoReturn:
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(678, 472)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(511, 408))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listView = QtWidgets.QListView(self.widget)
        self.listView.setObjectName("listView")
        self.gridLayout_2.addWidget(self.listView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(141, 411))
        self.widget_2.setMaximumSize(QtCore.QSize(261, 931))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listView_2 = QtWidgets.QListView(self.widget_2)
        self.listView_2.setObjectName("listView_2")
        self.gridLayout_3.addWidget(self.listView_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainMenu.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainMenu)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 678, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu_base = QtWidgets.QMenu(self.menuBar)
        self.menu_base.setObjectName("menu_base")
        self.obj_settings = QtWidgets.QMenu(self.menuBar)
        self.obj_settings.setObjectName("obj_settings")
        MainMenu.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainMenu)
        self.statusBar.setObjectName("statusBar")
        MainMenu.setStatusBar(self.statusBar)
        self.action_create_db = QtWidgets.QAction(MainMenu)
        self.action_create_db.setObjectName("action_create_db")
        self.action_connect_db = QtWidgets.QAction(MainMenu)
        self.action_connect_db.setObjectName("action_connect_db")
        self.action_settings = QtWidgets.QAction(MainMenu)
        self.action_settings.setObjectName("action_settings")
        self.action_exit = QtWidgets.QAction(MainMenu)
        self.action_exit.setObjectName("action_exit")
        self.action_syslog = QtWidgets.QAction(MainMenu)
        self.action_syslog.setObjectName("action_syslog")
        self.menu_base.addAction(self.action_create_db)
        self.menu_base.addAction(self.action_connect_db)
        self.menu_base.addSeparator()
        self.menu_base.addAction(self.action_syslog)
        self.obj_settings.addAction(self.action_settings)
        self.obj_settings.addSeparator()
        self.obj_settings.addAction(self.action_exit)
        self.menuBar.addAction(self.obj_settings.menuAction())
        self.menuBar.addAction(self.menu_base.menuAction())

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu) -> NoReturn:
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Controlcenter"))
        self.menu_base.setTitle(_translate("MainMenu", "База"))
        self.obj_settings.setTitle(_translate("MainMenu", "Настройки"))
        self.action_create_db.setText(_translate("MainMenu", "Создать базу данных"))
        self.action_connect_db.setText(_translate("MainMenu", "Подключить базу данных"))
        self.action_settings.setText(_translate("MainMenu", "Настройки пользователя"))
        self.action_exit.setText(_translate("MainMenu", "Выход"))
        self.action_syslog.setText(_translate("MainMenu", "Просмотр логов"))
